### ISSUE TITLE
Youtube regex parse error

### ISSUE THREAD

**Issue by egdv** [dertuxmalwieder/yaydl#11]
I have a simple fix for this error. Provide access to upstream and I can test direct upstream update as you have suggested?

```
     Running `target\debug\yaydl.exe https://youtu.be/jNQXAC9IVRw`
Fetching from YouTube.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (?:v=|\.be\/)(.*?)(&.*)*$
              ^^
error: unrecognized escape sequence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', src\handlers\youtube.rs:174:65
```
or fix it by deleting a char

```
let id_regex = Regex::new(r"(?:v=|\.be\/)(.*?)(&.*)*$").unwrap();
                                      ^--- fix: delete this backslash 1 char before e 

```

**Comment by dertuxmalwieder** [comment]
> Provide access to upstream and I can test direct upstream update as you have suggested?

Sure. Upstream registration should be enabled now. Create an account and I'll grant you access... :-)

(GitHub sync is every night.)

**Comment by egdv** [comment]
Github account?

**Comment by dertuxmalwieder** [comment]
As described in the README, the upstream repository [is here](https://code.rosaelefanten.org/yaydl/).

**Comment by egdv** [comment]
*edit for security reasons | dertuxmalwieder*

**Comment by dertuxmalwieder** [comment]
I granted you the *developer* flag. You **should**, in theory, be able to use it if I have not made a mistake. :-) 

Clone:
``fossil clone -A <username> https://<user>:<password>@code.rosaelefanten.org/yaydl`` 

Commit:
``fossil commit -m <message>`` 

Pull:
`` fossil update`` 

Hope it works - first time I actually let someone in.

**Comment by dertuxmalwieder** [comment]
Fixed, it seems. Pushed 0.11.2 to Crates.io, finally.. :)
