### ISSUE TITLE
YouTube download fails on Windows, but ok on Linux

### ISSUE THREAD

**Issue by egdv** [dertuxmalwieder/yaydl#12]
yaydl https://youtu.be/gIqsBUo82-Q  -v
Fetching from YouTube.
The requested video was found. Processing...
Title: Why is an 8-Track Tape Called an 8-Track Tape?
Starting the download.
Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)

yaydl --version
yaydl 0.11.2

**Comment by dertuxmalwieder** [comment]
Hmm. Is the generated file name not Windows-compatible?
What’s the name of the file on Linux?

**Comment by dertuxmalwieder** [comment]
[Fixed](https://code.rosaelefanten.org/yaydl/finfo?name=src/main.rs&ci=d02d554a31204b32&m=ee118d7c34841bbe), I guess.
