### ISSUE TITLE
possible to download with http proxy?

### ISSUE THREAD

**Issue by kiinoo** [dertuxmalwieder/yaydl#14]
see the title

**Comment by dertuxmalwieder** [comment]
In theory, 0.12.0 added proxy support. If it does not work for you, I’ll need more information.

**Comment by kiinoo** [comment]
thanks, I probably did not make it right. what I did is setting proxy like this (in windows):

    set HTTPS_PROXY=127.0.0.1:7890
    set HTTP_PROXY=127.0.0.1:7890

and then ran `yaydl <url>`

**Comment by dertuxmalwieder** [comment]
Proxy support is implemented per site. I haven’t found the time to add it to all of them yet, see e.g. https://github.com/dertuxmalwieder/yaydl/commit/b8374d636b3202d97e804fbd975df473194aff5d

Which site did you try? (I don’t use a proxy at home, so debugging is harder than you’d think right now…)

**Comment by kiinoo** [comment]
Youtube.

I've seen the .commit, but could not figure out how to use it by looking through code like this: `env_proxy::for_url(&url)`

**Comment by dertuxmalwieder** [comment]
Hmm. Basically, all calls to *ureq::* need to be wrapped in *env_proxy*. YouTube does not do that yet. I will try to fix it later, I’ll post here.

**Comment by dertuxmalwieder** [comment]
Potentially fixed upstream (untested)?
https://code.rosaelefanten.org/yaydl/vdiff?from=c6723756b0ba3f63&to=c115ce129d7a8a03

**Comment by dertuxmalwieder** [comment]
Closed due to no feedback.
