### ISSUE TITLE
YouTube Shorts Support

### ISSUE THREAD

**Issue by thomasvivas** [dertuxmalwieder/yaydl#15]
Refer to title

**Comment by dertuxmalwieder** [comment]
Sounds valid. Is there a documented API for those?

**Comment by thomasvivas** [comment]
It seems as if a YouTube Short is just any other YouTube video that can be viewed in two different ways, each with their own URL. The only thing that would need to be done is to get the video ID of the short and then just convert it to what a normal YouTube video would be.

Take for example this YouTube Short https://www.youtube.com/shorts/ZaDGYq6-UXc
It will take you to a specialized location in YouTube that is intended only for shorts and can allow you to scroll through other shorts, but the URL is different from a normal YouTube video.

If the URL is changed to https://www.youtube.com/watch?v=ZaDGYq6-UXc, you get precisely the same video just in a different location, and one that is able to be downloaded by yaydl.

This is just a matter of text manipulation in the program to convert the YouTube Short into a normal YouTube video URL that is already recognized by yaydl.

**Comment by dertuxmalwieder** [comment]
I see.

Latest code (0.12.2):

```
% ./target/debug/yaydl https://www.youtube.com/shorts/ZaDGYq6-UXc
Fetching from YouTube.
"yippe.mp4" successfully downloaded.
```

Am I missing something?

**Comment by thomasvivas** [comment]
My deepest apologies, I was previously running 0.11.4, but it now seems to work after updating to 0.12.2.

**Comment by dertuxmalwieder** [comment]
Don't worry. This actually reminded me to publish a new version to Cargo! :-)
