### ISSUE TITLE
Unable to download any video from YouTube

### ISSUE THREAD

**Issue by thomasvivas** [dertuxmalwieder/yaydl#17]
No matter what YouTube link is used, the following error occurs.
`The video could not be found. Invalid link?`
I suspect this may have something to do with the API key as the same version (0.12.2) was working approximately a week or so ago.

**Comment by dertuxmalwieder** [comment]
You are right. It looks like YouTube has decided to mostly "disable" the ancient-ish JSON-only API that `yaydl` uses in favor of a challenge-based approach. I probably won't have time to fix it over the weekend (I'll mostly be out of town)... help wanted. :-)
