### ISSUE TITLE
Add a "Deploy to Heroku" badge to the README

### ISSUE THREAD

**Issue by raisedhand** [dertuxmalwieder/yaydl#2]
Hi Cthulhux ,
please if it's possible make deploy to heroku button for free of monthly vps charge. also heroku have any buildpack you need like selenium , chrome headless , ffmpeg , or ...
waiting for your response
finest regards

**Comment by dertuxmalwieder** [comment]
That would require me to
1. investigate what a Heroku is,
2. find out how yaydl fits a Heroku,
3. care enough.

**Comment by dertuxmalwieder** [comment]
I have checked your GitHub history and your primary goal here seems to be to advertise Heroku.

Won't happen here, pal. Good luck elsewhere.
