### ISSUE TITLE
scinexx.de

### ISSUE THREAD

**Issue by bsbhro** [dertuxmalwieder/yaydl#21]
Hi, this try failed

RUST_BACKTRACE=1 yaydl https://www.scinexx.de/wp-content/uploads/s/o/sonnenwirbel3g.mp4
thread 'main' panicked at /home/bs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yaydl-0.16.0/src/handlers/voe.rs:30:34:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "response too big for into_string" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Thank you for this tool.

**Comment by dertuxmalwieder** [comment]
Ahoy,

I think there is a misunderstanding here: For downloading MP4 files *directly*, `yaydl` might be the wrong choice. (Try `wget` or `curl` instead!) I'm not sure if supporting direct downloads would exceed the goals of this project, especially given that parallelized downloads are still a TODO.

(Additionally, *scinexx* is not among the supported websites. Yet? But that's not relevant for this issue.)

**Comment by bsbhro** [comment]
Thank you. I now know how to use the tool correctly. 'wget' and 'curl' worked immediately.
