### ISSUE TITLE
Keep file on error

### ISSUE THREAD

**Issue by zuixalias** [dertuxmalwieder/yaydl#5]
There is this msg which is same as `youtube-dl` when a download from `music.youtube.com` is finished :
`'list' is not recognized as an internal or external command, operable program or batch file.`

`youtube-dl` keeps the file whereas `yay-dl` doesn't (even though the download is successful).

Please keep it/ add a flag to allow keeping it :)

**Comment by dertuxmalwieder** [comment]
Hmm. The command looks like it's not from `yaydl`. 😶

**Comment by zuixalias** [comment]
Hmm, it's works now...
Sometimes with random error it doesn't, but mostly working now.

**Comment by dertuxmalwieder** [comment]
yaydl *does* delete pre-conversion files though. I pushed 0.7.0 yesterday with an additional flag to change that. :-)

Random errors are because I need help to keep up with YouTube’s API…

**Comment by zuixalias** [comment]
Thanks!

**Comment by dertuxmalwieder** [comment]
You're welcome :-)
