### ISSUE TITLE
Adding new handler for a site

### ISSUE THREAD

**Issue by egdv** [dertuxmalwieder/yaydl#7]
Should I create a pull request?

**Comment by dertuxmalwieder** [comment]
Which site?

**Comment by egdv** [comment]
spankbang.com, copied and renamed xhamster.rs  then updated it. Used url path for filename and made sure it works with Windows also.

**Comment by dertuxmalwieder** [comment]
Sounds reasonable. I'd prefer a patch so I can integrate it upstream...?

(I wish that `yaydl` would **not** be known as a porn downloader... 😂)

**Comment by egdv** [comment]
I think merging the pull request does the same thing, integrate with upstream.

**Comment by dertuxmalwieder** [comment]
Merged into 0.11. Thank you.
